repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.5.0
    hooks:
      - id: sync-with-uv

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff # lint
        files: ^src/
      - id: ruff-format # format
        files: ^src/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        files: ^src/
        pass_filenames: false
